---
title: "APM466"
author: "Yanzhe Wang"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("jrvFinance")
```

## Q4

```{r}
# this data only contains clean prices of 11 selected bonds, using to calculate YTM
Clean=read.csv("/Users/37458/Desktop/APM466/clean1.csv", header=TRUE)
Clean
Clean=as.data.frame(Clean)
# this data only contains 11 bonds dirty prices (converted from clean in raw data) 
# the dirty price data is used to calculate spot and forward rates
Dirty=read.csv("/Users/37458/Desktop/APM466/dirty1.csv", header=TRUE)
Dirty=as.data.frame(Dirty)
```

```{r}
s=rep(1,10)
t=spotscolumnnames=yieldscolumnnames=fwdscolumnnames=rep(1,10)
v=rep(1,4)
RawSpots = RawYields = data.frame(s,s,s,s,s,s,s,s,s,s)

FinalYields = FinalSpots = data.frame(t,t,t,t,t,t,t,t,t,t)
Forwards = data.frame(v,v,v,v,v,v,v,v,v,v)

Dates = c("2021-01-18","2021-01-19","2021-01-20","2021-01-21","2021-01-22","2021-01-25","2021-01-26","2021-01-27","2021-01-28","2021-01-29")
```


```{r}
# YTM
#using jrvfinance
for (i in c(1:10)) 
{
  for (j in c(1:10))
  {
    #vars to input: (settle date, maturity, coupon rate, coupon freq, price, daycount,compounding freq, redemp value)
    RawYields[i,j]=bond.yield(Dates[j], Clean$Maturity.Date[i],
                              Clean$Coupon[i],freq=2,
                              Clean[i,j+9],
                              "ACT/ACT",comp.freq=2,redemption_value = 100)
  }
}
View(RawYields)
```

```{r}
####Spots####

#calculate the semi-ann spot rate within the first six months:
#2*[(price/(0.5*coupon + face)^(-1/2*TTM))-1]
for (i in 1:10)
{
  price=Dirty[1,9+i]
  coupon=Dirty[1,3]*100/2 
  # multiply by 100 for the notional value of the coupon,  div by 2 for semi-annual
  face=100
  maturityInMonths=Dirty[1,5]/12
  RawSpots[1,i]=2*((price/(coupon+face))^(-1/(2*maturityInMonths))-1) 
  #this gives semi-annual
}

#calculate spot rates for rest of time periods
for (i in c(2:10))
{
  for (j in c(1:10))
  {
    price=Dirty[i,9+j]
    coupon=Dirty$Coupon[i]*100/2 
    # mult by 100 for the notional value of the coupon,  div by 2 for semi-annual
    face=100
    coupons_PV=0 
    #initialize the present value of coupons
    maturityInMonths=Dirty$Months.until.Maturity[i]/12
    coupon_times = seq((6-Dirty$Months.since.Last.Coupon[i])/12,(Dirty$Months.until.Maturity[i]-1)/12,1/2)
    for (k in c(1:length(coupon_times)))
    {
      coupons_PV=coupons_PV+coupon*(1+RawSpots[k,j]/2)^(-2*coupon_times[k])
    }
    newprice=price-coupons_PV
    coupons_PV=0 
    #reset coupon present value
    RawSpots[i,j]=2*((newprice/(coupon+face))^(-1/(2*maturityInMonths))-1)
  }
}
View(RawSpots)
```


```{r}

#rename relevant columns for [Date]"

for (a in c(1:length(Dates)))
{
  spotscolumnnames[a] = c(paste("Spots for",Dates[a]))
  yieldscolumnnames[a] = c(paste("Yields for",Dates[a]))
  fwdscolumnnames[a] = c(paste("Forwards for",Dates[a]))
}
names(RawSpots)=names(FinalSpots)=spotscolumnnames
names(RawYields)=names(FinalYields)=yieldscolumnnames
names(Forwards)=fwdscolumnnames
Dirty=data.frame(Dirty,RawSpots)
```


```{r}
#Interpolation for yields and spots

#interpolate for n-month yield and n-month spot, where n is multiples of 6 up to 60
for (i in c(1:10))
{
  for (j in c(1:10))
  {
    FinalYields[j,i]=approx(Dirty$Months.until.Maturity,RawYields[[i]],xout=6*j)$y
    FinalSpots[j,i]=approx(Dirty$Months.until.Maturity,RawSpots[[i]],xout=6*j)$y
  }
}
rownames(FinalYields)=rownames(FinalSpots)=seq(6,60,6)

#Forwards#

#forward 1-yr, n-yr= 1 yr forward from n-yr spot

for (j in c(1:4))
{
  for (i in c(1:10))
  {
    n_yr=(1+FinalSpots[2*j,i]/2)^(2*j)
    one_yr_fwd=(1+FinalSpots[2+2*j,i]/2)^(2+2*j)
    Forwards[j,i]=2*((one_yr_fwd/n_yr)^(1/2)-1)
  }
}
```

```{r}
# remove null value 
FinalYields =  FinalYields[1:7, 1:10]
FinalSpots = FinalSpots[1:7, 1:10]
```

## Q5

```{r}
#covariance matrices for log-return of yields####
log_return_yields1=log_return_yields2=log_return_yields3=log_return_yields4=log_return_yields5=vector("numeric",9)

for (i in c(1:9))
{
  log_return_yields1[i]=log(FinalYields[2,i]/FinalYields[2,i+1])
  log_return_yields2[i]=log(FinalYields[4,i]/FinalYields[4,i+1])
  log_return_yields3[i]=log(FinalYields[6,i]/FinalYields[4,i+1])
  log_return_yields4[i]=log(FinalYields[8,i]/FinalYields[8,i+1])
  log_return_yields5[i]=log(FinalYields[10,i]/FinalYields[10,i+1])
}

log_returns_yields=data.frame(log_return_yields1,log_return_yields2,log_return_yields3,log_return_yields4,log_return_yields5)
covariance_of_log_returns=cov(log_returns_yields,log_returns_yields)

#covariance matrices for fwd rates
fwdrates12=fwdrates13=fwdrates14=fwdrates15=vector("numeric",9)
for(i in c(1:9))
{
  fwdrates12[i]=log(Forwards[1,i]/Forwards[1,i+1])
  fwdrates13[i]=log(Forwards[2,i]/Forwards[2,i+1])
  fwdrates14[i]=log(Forwards[3,i]/Forwards[3,i+1])
  fwdrates15[i]=log(Forwards[4,i]/Forwards[4,i+1])
}

fwdrates=data.frame(fwdrates12,fwdrates13,fwdrates14,fwdrates15)
covariance_of_fwdrates=cov(fwdrates,fwdrates)
```


## Q6


```{r}
#eigenitems of the above covariance matrices####
eigenitems_yield=eigen(covariance_of_log_returns[1:3, 1:3],symmetric=TRUE)
eigenitems_fwd=eigen(covariance_of_fwdrates[1:2, 1:2],symmetric=TRUE)
eigenitems_yield
eigenitems_fwd
```

##Plot

```{r}
pdf(file=paste(getwd(),"/YTM.pdf",sep=""),width=4,height=3.5)
plot(seq(6, 42, 6), FinalYields$`Yields for 2021-01-18`, type = "l", col = "blue", xlab="Months from January 2021",ylab="Yield in Decimal (semi-ann compounded)", main ="Yield Curves")
lines(seq(6, 42, 6), FinalYields$`Yields for 2021-01-18`, type = "l", col = "blue")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-19`, type = "l",col="green")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-20`,type = "l", col="red")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-21`,col="blueviolet")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-22`,col="violet")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-25`,col="yellowgreen")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-26`,col="sienna")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-27`,col="powderblue")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-28`,col="gold")
lines(seq(6,42,6),FinalYields$`Yields for 2021-01-29`,col="orange")
legend("topleft",Dates,lty=c(1,1), lwd=c(2,2),cex=.5, bty = "n", 
       col=c("blue","green","red","blueviolet","violet","yellowgreen","sienna","powderblue","gold","orange"))
dev.off()
```

```{r}
####Spot Plot####
pdf(file=paste(getwd(),"/Spot_plot.pdf",sep=""),width=4.5,height=4)
plot(seq(6,42,6),FinalSpots$`Spots for 2021-01-18`,type="l",col="blue", xlab="Months from January 2021",ylab="Spot in Decimal (semi-ann compounded)", main ="Spot Curves")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-19`,col="green")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-20`,col="red")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-21`,col="blueviolet")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-22`,col="violet")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-25`,col="yellowgreen")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-26`,col="sienna")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-27`,col="powderblue")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-28`,col="gold")
lines(seq(6,42,6),FinalSpots$`Spots for 2021-01-29`,col="orange")
legend("topleft",Dates,lty=c(1,1), lwd=c(2,2),cex=.5, bty = "n", 
       col=c("blue","green","red","blueviolet","violet","yellowgreen","sienna","powderblue","gold","orange"))
dev.off()
```


```{r}
####Forwards Plot####
Forwards = Forwards[1:2, 1:10]
pdf(file=paste(getwd(),"/Fwd_plot.pdf",sep=""),width=4.5,height=4)
plot(seq(1,2),Forwards$`Forwards for 2021-01-18`,type="l", col="blue",xlab="Years from 2021",ylab="Forward in Decimal (semi-ann compounded)", main ="1-Yr, N-Yr Forward Curves")
lines(seq(1,2),Forwards$`Forwards for 2021-01-19`,col="green")
lines(seq(1,2),Forwards$`Forwards for 2021-01-20`,col="red")
lines(seq(1,2),Forwards$`Forwards for 2021-01-21`,col="blueviolet")
lines(seq(1,2),Forwards$`Forwards for 2021-01-22`,col="violet")
lines(seq(1,2),Forwards$`Forwards for 2021-01-25`,col="yellowgreen")
lines(seq(1,2),Forwards$`Forwards for 2021-01-26`,col="sienna")
lines(seq(1,2),Forwards$`Forwards for 2021-01-27`,col="powderblue")
lines(seq(1,2),Forwards$`Forwards for 2021-01-28`,col="gold")
lines(seq(1,2),Forwards$`Forwards for 2021-01-29`,col="orange")
legend("topleft",Dates,lty=c(1,1), lwd=c(2,2),cex=.5, bty = "n", 
       col=c("blue","green","red","blueviolet","violet","yellowgreen","sienna","powderblue","gold","orange"))
dev.off()
```


